### ISSUE TITLE
Do we want to add "classic" component to the react-basic-hooks template?

### ISSUE THREAD

**Issue by paluh** [purescript-templates/react-basic-hooks#2]
Do we want to add _react-basic-classic_ dependency and an example component to this template (hooks can be mixed an matched with traditional "classic" components)?

Do we want to add separate template for _classic_?

**Comment by milesfrain** [comment]
I think this depends on what the common use case is.

A `-classic` dependency might be annoying for users who don't need it.

A separate template increases maintenance effort, but since that's more of a maintainer issue, I think that's the right way to go for user convenience.

**Edit:** But before adding anything, I think it would be good to determine whether there's any interest in a template featuring classic components. I suspect this is a rarer use-case, and the existing react docs describe what to do.

**Comment by paluh** [comment]
> A -classic dependency might be annoying for users who don't need it.

True.

> Edit: But before adding anything, I think it would be good to determine whether there's any interest in a template featuring classic components. I suspect this is a rarer use-case, and the existing react docs describe what to do.

So I'm closing it for now. If this topic was raised again I would happily help with the implementation.
